Lecture11 currency exchanger
wi9916/RockFood pull request #19
Opened 2021-08-11 14:56 UTC by wi9916

2021-08-11 15:05 UTC, wi9916 commented
привів до вигляду 10 завдання

2021-08-20 19:36 UTC, serhii-shkodenko requested changes
Поправ, будь ласка, ці зауваження.

2021-08-20 19:36 UTC, serhii-shkodenko commented on Interfaces/IExchangerable.cs
> +        Task<decimal> GetCurrencyAsync(string currencyName);
Краще, мабуть, дати назву не з валютою пов'язаною, а з курсом валют (ExchangeRate), бо метод в тебе називається `GetCurrencyAsync()`, а повертається з нього чомусь `Task<decimal>`.

2021-08-20 19:36 UTC, serhii-shkodenko commented on Models/CurrencyRate.cs
> +    public class CurrencyRate
Усі імена властивостей мають бути в PascalCase. Поправь будь-ласка, всі властивості у цьому класі.

2021-08-20 19:36 UTC, serhii-shkodenko commented on Services/CurrencyExchanger.cs
> +        private CurrencyRate Currency { get; set; }
Цю властивість краще конвертувати у поле, бо вона в тебе приватна і поправ неймінг, будь-ласка.

2021-08-20 19:36 UTC, serhii-shkodenko commented on Services/CurrencyExchanger.cs
> +        private string Date{ get; set; }
Цю властивість краще конвертувати у поле, бо вона в тебе приватна і поправ неймінг, будь-ласка.

2021-08-20 19:36 UTC, serhii-shkodenko commented on Services/CurrencyExchanger.cs
> +            if (DateTime.Today.AddDays(-1).ToString("DD-MM-yyyy") != Date)
Краще не конвертувати у стрінг тип. Просто зберігай DayTime і порівнюй, якщо треба.

2021-08-20 19:36 UTC, serhii-shkodenko commented on Services/CurrencyExchanger.cs
> +                new JsonSerializerOptions { IncludeFields = true });
Нащо ти включаєш поля у серіалізацію? Вони точно є в моделі? Якщо їх немає, то ця опція непотрібна.

2021-08-20 19:36 UTC, serhii-shkodenko commented on Services/CurrencyExchanger.cs
> +                "https://api.privatbank.ua/p24api/exchange_rates?json&date=01.12.2019?currency=CAD");
Тут ти завжди відправляєш запити, в яких в тебе одна і та сама дата і одна і та сама валюта. Тобто твоя логіка із кешуванням курсу не працює. При цьому в методі `GetCurrencyAsync() `в тебе є параметр з іменем валюти, було б логічніше прокидувати його і в  `GetNewCurrencyAsync()`.

2021-08-20 19:36 UTC, serhii-shkodenko commented on Services/ResidentsOperation.cs
> +        private readonly IMemoryCachable<IPersonable> _memoryCache;
Одрук. Треба `Cacheable`. Поправ, будь-ласка, по всьому проекту.

2021-08-20 19:36 UTC, serhii-shkodenko commented on Services/StorageOperation.cs
> +        public StorageOperation(IStoredable sameFoods, ILogger logger, IDataStorage dataStorage, IMemoryCachable<IFoodable> memoryCach, IExchangerable currencyExchanger)
Одрук. Треба `memoryCache`.

2021-08-20 19:36 UTC, serhii-shkodenko commented on Services/DialogInShop.cs
> +            _sameStorage.OutputInfoAboutFoodAsync();
Тут ти не очікуєш результат виконання твого асинхронного методу. Тому, виконання методу `DialogChooseProduct() `буде продовжено без виконання методу `OutputInfoAboutFoodAsync()`.

2021-08-20 19:36 UTC, serhii-shkodenko commented on Services/DialogInShop.cs
> +            _sameStorage.OutputInfoAboutFoodAsync(foodId);
Тут ти не очікуєш результат виконання твого асинхронного методу. Тому, виконання методу `DialogBuyProduct() `буде продовжено без виконання методу `OutputInfoAboutFoodAsync()`.

2021-08-21 19:00 UTC, serhii-shkodenko approved these changes
Виглядає добре. Можна мержити.

2021-08-21 19:27 UTC, merged