Lecture2
wi9916/RockFood pull request #2
Opened 2021-04-15 19:42 UTC by wi9916

2021-04-16 08:49 UTC, wi9916 commented
Lecture2 start

2021-04-17 20:57 UTC, serhii-shkodenko requested changes
Невеличкі зауваження по іменам.

2021-04-17 20:57 UTC, serhii-shkodenko commented on Models/Company.cs
> +    class Company
Не вистачає модификаторів доступу. Продивись весь ПР, будь ласка.

2021-04-17 20:57 UTC, serhii-shkodenko commented on Models/Company.cs
> +        public int companyId { get; set; }
Назви властивостей у C# йменуються у `PascalCase`. Продивись весь ПР, будь ласка.

2021-04-17 20:57 UTC, serhii-shkodenko commented on Models/Container.cs
> +    class Container: Product
Створювати пусті класи на всяк випадок, то не дуже хороша практика. Коли виникне необхідність, тоді вже треба це робити.

2021-04-18 10:41 UTC, wi9916 commented
виправив зауваження додав список з типами їжі в Food

2021-04-18 12:24 UTC, serhii-shkodenko requested changes

2021-04-18 12:24 UTC, serhii-shkodenko commented on Models/Order.cs
> +        public bool OrderStatus { get; set; }
У статуса замовлення може бути набагато більше станів, ніж просто доставлений/недоставлений, наприклад, в дорозі, в обробці, отримання підтверджено і так далі. Тут треба інший тип даних.

2021-04-18 12:24 UTC, serhii-shkodenko commented on Models/Order.cs
> +        public DateTime DateDelivery { get; set; }
Англійською буде краще `DeliveryDate`, або `DateOfDelivery`. Перший варіант більш бажаний.

2021-04-18 12:24 UTC, serhii-shkodenko commented on Models/Order.cs
> +        public DateTime DateCreate { get; set; }
Можливо тут краще назвати цю властивість `Created`.

2021-04-18 12:24 UTC, serhii-shkodenko commented on Models/Person.cs
> +        public string AboutPerson { get; set; }
Достатньо буде просто `About`.

2021-04-18 12:24 UTC, serhii-shkodenko commented on Models/Product.cs
> +        public int BompanyId { get; set; }
Тут мабуть одрук: треба `CompanyId` замість `BompanyId`.

2021-04-18 12:24 UTC, serhii-shkodenko commented on Models/Product.cs
> +        public string AboutItem { get; set; }
Достатньо буде просто `About`.

2021-04-18 12:24 UTC, serhii-shkodenko commented on Models/Product.cs
> +        public decimal Prise { get; set; }
Тут одрук: треба `Price` замість `Prise`.

2021-04-18 12:24 UTC, serhii-shkodenko commented on Models/Seller.cs
> +        public double RatingFromCastomers { get; set; }
Одрук. Має бути `Customers`.

2021-04-18 12:24 UTC, serhii-shkodenko commented on Models/Company.cs
> +        public string AboutCompany { get; set; }
Достатньо буде просто `About`.

2021-04-18 12:24 UTC, serhii-shkodenko commented on Models/DeliveryMan.cs
> +        public bool WorkNow { get; set; }
Мабуть буде краще назвати цю валстивість як `IsAvailable`, або щось на кшталт. Подивись, будь ласка, [відповідну конвенцію](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-properties).

2021-04-18 12:24 UTC, serhii-shkodenko commented on Models/Food.cs
> +    public enum ProductType
Зверну увагу, що тип продуктів буде дуже часто змінюватися, щось будет додаватися, щось зникати з продажу. Кожного разу вносити зміни в код для досить тривіальної операції не є оптимальним рішенням. Краще розробити для цього окремий клас.

2021-04-18 16:45 UTC, wi9916 commented
виправив зауваження з назвами и створив клас для опису типів їжі

2021-04-18 16:56 UTC, serhii-shkodenko requested changes

2021-04-18 16:56 UTC, serhii-shkodenko commented on Models/Company.cs
> +        public int CompanyId { get; set; }
Це поле буде достатньо назвати просто `Id`. Зрозуміло, що воно стосується саме компанії.

2021-04-18 16:56 UTC, serhii-shkodenko commented on Models/Order.cs
> +        public int OrderId { get; set; }
Це поле буде достатньо назвати просто `Id`. Зрозуміло, що воно стосується саме замовлення.

2021-04-18 16:56 UTC, serhii-shkodenko commented on Models/Order.cs
> +        public OrderStatus orderStatus { get; set; }
Одрук, треба `OrderStatus`.

2021-04-18 16:56 UTC, serhii-shkodenko commented on Models/Person.cs
> +        public int PesonId { get; set; }
Це поле буде достатньо назвати просто `Id`. Зрозуміло, що воно стосується саме людини.

2021-04-18 16:56 UTC, serhii-shkodenko commented on Models/Product.cs
> +        public int ProductId { get; set; }
Це поле буде достатньо назвати просто `Id`. Зрозуміло, що воно стосується саме людини.

2021-04-18 16:56 UTC, serhii-shkodenko commented on Models/Food.cs
> +        public string ProductType { get; set; }
Це поле має бути типу `ProductType`.

2021-04-18 16:56 UTC, serhii-shkodenko commented on Models/Food.cs
> +    public class ProductType : IEnumerable
Цей тип має нести інформацію про тип продукції, наприклад, назву позиції, її ціну, ціну за доставку, податки і таке інше.

2021-04-18 17:37 UTC, wi9916 commented on Models/Food.cs
> +        public string ProductType { get; set; }
Я хочу зробити клас продукт тайп для збереження інформації про саме тип продуктів в загальному, можливо звязати через ід якщо взяти більше полів. Наприклад якщо тип салат то додати столові прибори, але такий підхід мені неподобається. Планую покищо зберігати там назви типів їжі як для автозаповнення пункту тип їжі в класі фуд так і для навігації по сайту й для різних вибірок і фільтрів

2021-04-18 17:39 UTC, wi9916 commented on Models/Food.cs
> +    public class ProductType : IEnumerable
Власне планую зберігати тільки список типів їжі на приклад з списком але з можливістю додавати нові позиції

2021-04-18 18:08 UTC, wi9916 commented
Виправив назви змінних. По класу Food дискунсійно.

2021-04-19 18:59 UTC, wi9916 commented
Змінив ліст на Іліст

2021-04-20 20:59 UTC, serhii-shkodenko commented on Models/Food.cs
> +        public string ProductType { get; set; }
Добре. Оскільки вже є тип `ProductType`, то використання такого самого імені збиває з пантелику. Я пропоную назвати цю властивість `ProductTypeName`, `ProductDisplayName`, абощо.

2021-04-20 21:05 UTC, wi9916 commented
нове імя для зберігання можливих варіантів типів їжі

2021-04-20 21:12 UTC, serhii-shkodenko commented on Models/Food.cs
> +    public class ProductType : IEnumerable
Ок, тоді пропоную таке. Складність у тому, що ми ще не проходили колекції:

1. Переназвати цей клас на `ProductCollection`, реалізувати у ньому не `IEnumerable`, а `ICollection`. 
2. Поле `ProductTypes` переназвати на `_productsStore` і зробити його приватним.
3. Додати методи для додавання у колекцію і читання з неї.

2021-04-20 21:20 UTC, wi9916 commented
я правильно зрозумів?

2021-04-20 21:29 UTC, wi9916 commented
можливо я покижо лишу поле string? А колекцыю вже потым буду реалызовувати?

2021-04-20 21:29 UTC, wi9916 commented
видалю клас ProductCollection?

2021-04-20 22:18 UTC, serhii-shkodenko commented
> видалю клас ProductCollection?

В принципі його можна віднести до третього завдання. Тому можна видалити.

2021-04-20 22:18 UTC, serhii-shkodenko commented
> можливо я покижо лишу поле string? А колекцыю вже потым буду реалызовувати?

Це хороше рішення.

2021-04-21 05:02 UTC, wi9916 commented
Видалив клас лишив стрінг властивість

2021-04-21 18:45 UTC, wi9916 commented
Можна мержити?

2021-04-21 20:58 UTC, serhii-shkodenko approved these changes
Виглядає добре, можна мержити.

2021-04-22 18:25 UTC, merged