Lecture 3
wi9916/RockFood pull request #3
Opened 2021-04-20 22:16 UTC by wi9916

Start task 3

2021-04-21 17:21 UTC, wi9916 commented
Task 3

2021-04-22 18:39 UTC, serhii-shkodenko requested changes

2021-04-22 18:39 UTC, serhii-shkodenko commented on Shop.cs
> +                var kay = Console.ReadLine().ToString();
Одрук, потрібно `key`.

2021-04-22 18:39 UTC, serhii-shkodenko commented on Shop.cs
> +            bool success = Decimal.TryParse(text, out price);
Буде доречним використати тут неявну типізацію за допомогою `var`.

2021-04-22 18:39 UTC, serhii-shkodenko commented on Shop.cs
> +            var price = new decimal();
Краще буде decimal price = default;

2021-04-22 18:39 UTC, serhii-shkodenko commented on Shop.cs
> +    public class Shop: Storage
Некоректна назва класу. Він займається зчитуванням введених користувачем даних, їх обробкою та виводом результатів. Зі сформульованого мною списку завдань для класу видно, що він порушує Single Responsibility Prinsiple. Подумай, як можна покращити структуру коду.

2021-04-22 18:44 UTC, wi9916 commented on Shop.cs
> +    public class Shop: Storage
Замінити Shop на декылька класів для кожної конкретної задачі?

2021-04-22 18:48 UTC, wi9916 commented on Shop.cs
> +    public class Shop: Storage
чи ще розділити покупку та завезення товарів?

2021-04-22 20:07 UTC, wi9916 commented
Змінив класи для діалогів в магазині роботі на складі. Тепер в класі DialogInShop діалоги для купівлі товару завозу товару та створенню нового покупця. А в Storage робота з товарами
 Додав окремий клас для виводу інформації.

2021-04-22 20:16 UTC, wi9916 commented
Данні про покупців та обробка цих данних тепер в DialogInShop

2021-04-22 20:24 UTC, wi9916 commented
забув продивитися типи змінних в коді
(де неявна і тд)

2021-04-22 20:37 UTC, wi9916 commented
Створив новий клас для роботи з клієнтами

2021-04-23 17:29 UTC, wi9916 commented
или добавить интерфейсы?

2021-04-25 20:10 UTC, wi9916 commented
a few new sings about Interface and Exception

2021-04-25 21:05 UTC, serhii-shkodenko requested changes

2021-04-25 21:05 UTC, serhii-shkodenko commented on Exception/CustomException.cs
> +    class CustomException : Exception
Не хватает модификатора доступа.

2021-04-25 21:05 UTC, serhii-shkodenko commented on Exception/CustomException.cs
> +    class CustomException : Exception
Имя класса для исключения не дает понять, зачем этот класс нужен, и что это за исключение. Во время встречи это имя было выбрано в демонстрационных целях.

2021-04-25 21:05 UTC, serhii-shkodenko commented on Interfaces/IDialogInShop.cs
> +
Пустая строка. Лучше удалить.

2021-04-25 21:05 UTC, serhii-shkodenko commented on Interfaces/IDialogInShop.cs
> +    public interface IDialogInShop
Озакомься, пожалуйста, с конвенцией по поводу имен для интерфейсов. Она находится по адресу https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces

Возможно, этот интерфейс лучше назвать `IDialogable`.

2021-04-25 21:05 UTC, serhii-shkodenko commented on Services/DialogInShop.cs
> +        public Residents SameCostumers { get; set; }
Опечатка в слове `Costumers`.

2021-04-25 21:05 UTC, serhii-shkodenko commented on Services/Residents.cs
> +            try                      // try/catch only for examle
Этот блок try...catch лучше удалить. Его использование не продиктовано безнес логикой, на что указывает этот комментарий.

2021-04-27 17:02 UTC, serhii-shkodenko requested changes

2021-04-27 17:02 UTC, serhii-shkodenko commented on Program.cs
>              Console.WriteLine("Hello World!");
Эту строку можно вполне удалить, она не относится к приложению.

2021-04-27 17:02 UTC, serhii-shkodenko commented on Services/DialogInShop.cs
> +        public Storage SameStorage { get; set; }
Публичные свойства в классах моделях лучше использовать очень осторожно, потому что они нарушают сокрытие, а с ним и инкапсуляцию. Здесь лучше подойдет использование зависимости. Чтобы ее применить:
1. Создать конструктор, в параметрах которого указать объект, который будет содержать класс, управляющий заполнением/удалением данных. Зависимость должна быть выражена через интерфейс. 
2. В конструкторе сохранить из параметра входящую зависимость в приватное `readonly` поле. 
3. В дальнейшем, при необходимости удалить/добавить данные, пользоваться методами этой зависимости. 
Просмотри весь ПР, пожлауйста, на предмет этого и поправь

2021-04-29 21:40 UTC, serhii-shkodenko requested changes
Виправ, будь ласка, ці зауваження і скоріше всього будет апрув, якщо не знайду чогось важливого.

2021-04-29 21:40 UTC, serhii-shkodenko commented on Services/DialogInShop.cs
> +        private readonly IStoredable SameStorage;
Приватні поля мають йменуватися в `camelCase`.

2021-04-29 21:40 UTC, serhii-shkodenko commented on Services/DialogInShop.cs
> +        private readonly IResidentable SameCustomers;
Приватні поля мають йменуватися в `camelCase`.

2021-04-29 21:40 UTC, serhii-shkodenko commented on Services/Residents.cs
> +            return true;
Цей метод цілком можна зробити `void`, тому що значення, що повертається з методу, не використовується у конструкторі.

2021-04-29 21:40 UTC, serhii-shkodenko commented on Services/Storage.cs
> +        public bool PutNewFood(Food food)
Методи для маніпуляцій з даними краще винести в окремий клас.

2021-04-30 07:28 UTC, wi9916 commented on Services/Storage.cs
> +        public bool PutNewFood(Food food)
так це і є клас для маніпулювання данними. Тут 3 методи додавання продукта, вілучення продукта, і виведення інформації про продукт

2021-04-30 07:29 UTC, wi9916 commented on Services/Storage.cs
> +        public bool PutNewFood(Food food)
і для тестування метод для заповнення початковими данними

2021-04-30 07:32 UTC, wi9916 commented
виправив імена і тип метода

2021-04-30 09:13 UTC, wi9916 commented
Створив новий клас для роботи з данними

2021-04-30 23:30 UTC, serhii-shkodenko requested changes

2021-04-30 23:30 UTC, serhii-shkodenko commented on Services/DialogInShop.cs
> +        public DialogInShop()
Цей конструктор краще видалити.

2021-04-30 23:30 UTC, serhii-shkodenko commented on Services/DialogInShop.cs
> +            var customerId = new int();
Цей код:

```
            var customerId = new int();

            var success = Int32.TryParse(text, out customerId);
            if (success)
            {
                if (sameCustomers.OutputInfoAboutCustomer(customerId))           
                    DialogChooseProduct(customerId);
                else
                    Speaker.Output("Customer Choose Error", "Error");
            }
```
можна рівнозначно замінити на:

            
            if (int.TryParse(text, out var customerId))
            {
                if (sameCustomers.OutputInfoAboutCustomer(customerId))
                    DialogChooseProduct(customerId);
                else
                    Speaker.Output("Customer Choose Error", "Error");
            }

У ПР є також інші аналогічні місця, поправ, будь ласка їх.

2021-04-30 23:30 UTC, serhii-shkodenko commented on Services/DialogInShop.cs
> +            var success = Int32.TryParse(text, out customerId);
Замість CLR типу Int32 краще використовувати його C# аліас. Перевір, будь ласка, весь ПР.

2021-04-30 23:30 UTC, serhii-shkodenko commented on Services/ResidentsOperation.cs
> +                person.Id = storage.Customers.Count();
Загальноприйнято, що Id починаються з 1, а не з 0. Ця логіка буде продукувати саме 0.

Цей код також має іншу суттєву ваду.
Припустимо, є список:
Id = 0,
Id = 1,
Id = 2.

Якщо ти видалиш елемент зі списку посередині, то тоді список стане таким:
Id = 0,
Id = 2.

Твоя логіка призведе до того, що після додавання у список нового елемента, він перетвориться на:
Id = 0,
Id = 2,
Id = 2.

Тому краще знаходити максимальний Id и додавати до нього одиницю, щоб не було Id = 0.

Поправ, будь ласка, по вьому ПР.

2021-04-30 23:30 UTC, serhii-shkodenko commented on Services/ResidentsOperation.cs
> +            var index = storage.Customers.FindIndex(f => f.Id == customerId);
Цей код можна переписати так:
```
var customer = storage.Customers.FirstOrDefault(f => f.Id == customerId);

if(customer is null)
{
    return false;
}
Speaker.Output("Person Id - " + customer.Id.ToString() + " Name - " + customer.Name);
return true;
```

Переглянь увесь ПР, будь ласка.

2021-04-30 23:30 UTC, serhii-shkodenko commented on Services/StorageOperation.cs
> +        public StorageOperation()
Цей конструктор краще видалити.

2021-05-01 20:33 UTC, wi9916 commented
виправив зауваження

2021-05-01 23:40 UTC, wi9916 commented on Services/DialogInShop.cs
> +            var success = Int32.TryParse(text, out customerId);
надыюсь правильно зрозумыв помилку

2021-05-01 23:52 UTC, serhii-shkodenko approved these changes
Виглядає добре. Можна мержити.

2021-05-03 16:11 UTC, merged