Lecture5
wi9916/RockFood pull request #4
Opened 2021-05-01 23:38 UTC by wi9916

Start

2021-05-01 23:42 UTC, wi9916 commented
вся програма в останньому оновленны start до того 3 завдання

2021-05-01 23:42 UTC, wi9916 commented
я неправильно створив гілку?

2021-05-04 21:50 UTC, serhii-shkodenko requested changes

2021-05-04 21:50 UTC, serhii-shkodenko commented on Services/ContactInfoValidator.cs
> +        private readonly static string paternAddress = @"(^\w{1,}\s\w{1,}[,]\s\w{1,}\.\s\d{1,}[,]\s\w{1,}\.\s\d{1,}$)|" +
Цей регулярний вираз не працює, ні в Visual Studio Code, ні на regexr.com. Поправ, будь ласка.

2021-05-04 21:50 UTC, serhii-shkodenko commented on Services/ContactInfoValidator.cs
> +            if (!Regex.IsMatch(address, paternAddress, RegexOptions.IgnoreCase))
`Regex.IsMatch` повертає булеве значення, тож буде достатньо у тілі методу написати просто:
`return Regex.IsMatch(address, paternAddress, RegexOptions.IgnoreCase);`

2021-05-04 21:50 UTC, serhii-shkodenko commented on Services/ContactInfoValidator.cs
> +            if(!Regex.IsMatch(phoneNumber, paternPhone, RegexOptions.IgnoreCase))
`Regex.IsMatch` повертає булеве значення, тож буде достатньо у тілі методу написати просто:
`return Regex.IsMatch(phoneNumber, paternPhone, RegexOptions.IgnoreCase);`

2021-05-05 08:38 UTC, wi9916 commented
переробив на явны символи regex , дивно що в мене працювала і стара версія. Можливо через наявність російської локалі

2021-05-05 19:54 UTC, serhii-shkodenko requested changes
Вираз у мене все одно не запрацював.
Загалом, код став чистішим.

2021-05-05 19:54 UTC, serhii-shkodenko commented on Services/ContactInfoValidator.cs
> +        private readonly static string paternPhone = @"(^\+\d{3}\(\d{2}\)\d{3}\s\d{2}\s\d{2}$)|"+
У слові `patern` дві букви `t`.

2021-05-05 19:54 UTC, serhii-shkodenko commented on Services/ContactInfoValidator.cs
> +        private readonly static string paternAddress = @"(^[А-я]{1,}\s[А-я]{1,}[,]\s[А-я]{1,}\.\s\d{1,}[,]\s[А-я]{1,}\.\s\d{1,}$)|" +
У слові `patern` дві букви `t`.

2021-05-05 19:54 UTC, serhii-shkodenko commented on Services/ContactInfoValidator.cs
> +            return Regex.IsMatch(phoneNumber, paternPhone, RegexOptions.IgnoreCase);
У слові `patern` дві букви `t`.

2021-05-05 19:54 UTC, serhii-shkodenko commented on Services/ContactInfoValidator.cs
> +            return Regex.IsMatch(address, paternAddress, RegexOptions.IgnoreCase);
У слові `patern` дві букви `t`.

2021-05-05 19:54 UTC, serhii-shkodenko commented on Services/ContactInfoValidator.cs
> +        private readonly static string paternAddress = @"(^[А-я]{1,}\s[А-я]{1,}[,]\s[А-я]{1,}\.\s\d{1,}[,]\s[А-я]{1,}\.\s\d{1,}$)|" +
В мене як і раніше, виразне працює. 
![Screenshot 2021-05-05 225046](https://user-images.githubusercontent.com/69808191/117200743-816d9500-adf4-11eb-80b8-37c6e1cd8b8a.png)

Загалом можна обійтися набагато коротшим виразом.

2021-05-05 19:54 UTC, serhii-shkodenko commented on Services/ContactInfoValidator.cs
> +        private readonly static string paternAddress = @"(^[А-я]{1,}\s[А-я]{1,}[,]\s[А-я]{1,}\.\s\d{1,}[,]\s[А-я]{1,}\.\s\d{1,}$)|" +
Спробуй `\w`.

2021-05-05 20:51 UTC, serhii-shkodenko requested changes

2021-05-05 20:51 UTC, serhii-shkodenko commented on Services/ContactInfoValidator.cs
> +        private readonly static string patternPhone = @"^\+?\d{2}?\d\(?(\d{2})|(\s)\)?\d{3}\s?\d{2}\s?\d{2}";
А тепер поламався вираз для телефонів
![Screenshot 2021-05-05 234906](https://user-images.githubusercontent.com/69808191/117207430-9c440780-adfc-11eb-96d0-55cc9aad7c46.png)

2021-05-05 21:34 UTC, serhii-shkodenko approved these changes
Виглядає добре. Можна мержити.

2021-05-07 15:08 UTC, merged