Lecture 6
wi9916/RockFood pull request #5
Opened 2021-05-14 21:15 UTC by wi9916

2021-05-14 21:46 UTC, wi9916 commented
окрема папка з файлами для повідомлень та окремі файли при змінах на складах продуктів або списку покупців

2021-05-17 15:33 UTC, wi9916 commented
змінив логіку для виклика логгера

2021-05-17 19:23 UTC, serhii-shkodenko requested changes

2021-05-17 19:23 UTC, serhii-shkodenko commented on Interfaces/IWorkingWithFilable.cs
> +    public interface IWorkingWithFilable
Загальноприйнятим для логера є ім'я ILogger для ынтерфейсу та Logger для класу. Коли хтось сторонный буде читати твій код, то одразу зрозуміє, що це і навіщо. Тому краще зміни назву як для інтерфейсу, так і для класу.

2021-05-17 19:23 UTC, serhii-shkodenko commented on Interfaces/IWorkingWithFilable.cs
> +        public void AppendLine(string fileName, string infoToWrite);
Запис інформації для логу може відбуватися куди завгодно. Це може бути файл, це може бути якийсь ресурс у мережі, куди посилаються дані, абощо. Тому, вагомим для інтерфейсу логера є лише методи, які дозволяють логірувати інформацію. Tе, куди вона буде чи записана чи передана по мережі, це вже деталь реалізації, яку буде містити класс. 

Тобто тут можуть бути методи на кшалт:
```
Log(string information);
Log(string information, DateTime createdAt);
```

Будь ласка вдоскональ інтерфейс і зроби відповідні зміни, де ти його використовуєш.

2021-05-17 20:21 UTC, wi9916 commented
Змінив назви логера, змінив інтерфейс та його реалізацію на більш абстрактну

2021-05-17 20:27 UTC, wi9916 commented
Краще такий варіант де запис в файл відбуваеться в окремих методах? Чи де робота в самому методі log?

2021-05-18 23:01 UTC, serhii-shkodenko requested changes

2021-05-18 23:01 UTC, serhii-shkodenko commented on Interfaces/ILogger.cs
> +        public void log(string information, string message);
Модифікатор доступу `public` встановлюється за замовченням для членів інтерфейсу, тому його опускають.

2021-05-18 23:01 UTC, serhii-shkodenko commented on Services/Logger.cs
> +        public void log(string information, string message)
Методи мають йменуватися у `PascalCase`.

2021-05-18 23:01 UTC, serhii-shkodenko commented on Services/Logger.cs
> +                information + DateTime.Today.ToString("d") + ".txt"
Краще, щоб в імені файлу була повна дата, тобто день, місяць і рік.

2021-05-19 09:36 UTC, wi9916 commented
виправив модифікатори доступу в інтерфейсі та формат дати 15-12-1999

2021-05-19 09:45 UTC, serhii-shkodenko requested changes
Ще попрошу це виправити і скоріше за все, буде апрув.

2021-05-19 09:45 UTC, serhii-shkodenko commented on Services/Logger.cs
> +                information,
Я розумію так, що ти хочеш логувати інформацію з урахуванням важливості повідомлення, щоб потім можна було простіше знаходити те, що потрібно. Це правильно. Проте твоя реалізація створює під кожний новий рівень повідомлення окремий файл. Зазвичай все роблять трохи по іншому: створюють один файл за період і для кожного повідомлення вже вказують, що то за тип інформації. 

До того ж, твоя реалізація дозволяє передати у параметрі `information` будь-який рядок, це буде мати наслідком те, що ім'я файлу може складатися з величезної кількості символів, а оскільки ти не знаєш, що за файлова система в тебе на диску, то може виникнути виключна ситуація через занадто велике ім'я. 

Тому я пропоную створити якусь `enum`, де будуть типи іномрації вказані, наприклад `Debug`, `Information`, `Error` і для кожного повідомлення просто вказувати цей тип у методі `Log (LogLevel logLevel, string message)`.

2021-05-19 09:56 UTC, wi9916 commented on Services/Logger.cs
> +                information,
ні я просто зробив окрему папку для логера

2021-05-19 09:56 UTC, wi9916 commented on Services/Logger.cs
> +                information,
а так файл один на день

2021-05-19 09:57 UTC, wi9916 commented on Services/Logger.cs
> +                information,
але ідея додати окремий модифікатор для типу повідомлень цікава

2021-05-19 10:00 UTC, wi9916 commented on Services/Logger.cs
> +                information,
папку перейменую на Logger

2021-05-19 10:04 UTC, serhii-shkodenko commented on Services/Logger.cs
> +                information,
Наскільки я зрозумів твій код, файл не один на день. В тебе створюється файл path/something18_15_2021.txt, твоя реалізація дозволяє також створювати файли path/something_else_18_15_2021.txt і таке інше. 

Також вона залежить від того, наскільки ти коректно передав параметр `information` у метод:ти можеш передати `something`, а можеш `somethin` і буде вже інший файл, хоча за ту ж дату. Крім того, розміщення у папці не може вплинути на можливість виникнення багу із дуже довгим ім'ям файлу.

2021-05-19 10:05 UTC, serhii-shkodenko commented on Services/Logger.cs
> +                information,
Тому,  я пропоную, або повністю прибрати параметр information, або зробити enum.

2021-05-19 11:35 UTC, wi9916 commented
забрав information та додав запис ерорів в лог

2021-05-20 21:18 UTC, serhii-shkodenko requested changes

2021-05-20 21:18 UTC, serhii-shkodenko commented on Interfaces/ILogger.cs
> +        void Log(string information, string message, MessageTypes messageTypes = MessageTypes.None);
Ти зробив тип для повідомлення логу, тому параметр `information` вже непотрібний. Прибери його, будь ласка.

2021-05-20 21:18 UTC, serhii-shkodenko commented on Models/MessageTypes.cs
> +        None,
У типах повідомлень вказані типи, які стосуються різних категорій. Так, Error - це про помилки виконання програми, а Resident - шар програми, де виникла певна подія. Краще так не змішувати. Зазвичай логери мають типи повідомлень такі:
```
Error,
Information, 
Warning,
Debug
```

Але передавати в логер інформацію про місце виникнення події - це хороша ідея. Це можна зробити прямо в меседжі, використавши `nameof()`, наприклад. 

Думаю, найдоцільніше буде повністю прибрати Storage (до речі, тут одрук, немає останньої букви) і Resident типи, а інформацію про місце події передавати вже у повідомленні.

2021-05-20 21:18 UTC, serhii-shkodenko commented on Program.cs
> +            DialogInShop dialog = new DialogInShop(new StorageOperation(new Storage(), new Logger()), new ResidentsOperation(new Residents(), new Logger()));
Використовуй, будь ласка, неявну типізацію змінних за допомогою`var`.

2021-05-20 21:18 UTC, serhii-shkodenko commented on Services/Logger.cs
> +            var folderPath = Path.Combine(pathParts);
Насправді, ця змінна тобі не потрібна, ти одразу можеш передати в `filePath` масив `pathParts`.

2021-05-21 05:11 UTC, wi9916 commented on Services/Logger.cs
> +            var folderPath = Path.Combine(pathParts);
Але збирати шлях всеодно треба. А так зразу вмдно де шлях папки де шлях файлу.

2021-05-21 05:23 UTC, wi9916 commented on Interfaces/ILogger.cs
> +        void Log(string information, string message, MessageTypes messageTypes = MessageTypes.None);
А його і нема це старий варіант коду

2021-05-21 05:29 UTC, wi9916 commented on Services/Logger.cs
> +            var folderPath = Path.Combine(pathParts);
і його прийдеться створювати 2 рази що призведе до можливої помилки якщо ми колись змінемо шлях в одному методі а в 2-у забудемо

2021-05-21 05:32 UTC, wi9916 commented on Services/Logger.cs
> +            var folderPath = Path.Combine(pathParts);
і прийдеться декілька разів його збирати

2021-05-21 07:42 UTC, wi9916 commented on Services/Logger.cs
> +            var folderPath = Path.Combine(pathParts);
я використовую folderPath  для створення папки

2021-05-21 09:06 UTC, serhii-shkodenko commented on Services/Logger.cs
> +            var folderPath = Path.Combine(pathParts);
Ок, приймається.

2021-05-21 09:07 UTC, serhii-shkodenko approved these changes
Виглядає добре, можна мержити.

2021-05-29 06:40 UTC, merged