Lecture7
wi9916/RockFood pull request #6
Opened 2021-05-18 01:29 UTC by wi9916

початок

2021-05-18 01:30 UTC, wi9916 commented
початок 7 завдання

2021-05-28 21:59 UTC, serhii-shkodenko requested changes

2021-05-28 21:59 UTC, serhii-shkodenko commented on Interfaces/ISerializable.cs
> +        void Serialization<T>(T obj);
Методи в C# йменуться так, щоб в назві було дієслово, тому краще `Serialize<T>(T obj)`.

2021-05-28 21:59 UTC, serhii-shkodenko commented on Interfaces/ISerializable.cs
> +        T Desialization<T>(T obj);
Методи в C# йменуться так, щоб в назві було дієслово, тому краще `Desialization<T>(T obj)`.

2021-05-28 21:59 UTC, serhii-shkodenko commented on Interfaces/ISerializable.cs
> +        bool CheckFile();
А який же файл перевіряється? Мабуть, краще додати шлях до нього?

2021-05-28 22:00 UTC, serhii-shkodenko commented
Будь ласка, вмержи попереднє завдання, щоб я не перевіряв те, що вже перевірене.

2021-05-29 06:45 UTC, wi9916 commented on Interfaces/ISerializable.cs
> +        T Desialization<T>(T obj);
Desialization і було)))
Desialize можливо?

2021-05-29 06:56 UTC, wi9916 commented on Interfaces/ISerializable.cs
> +        bool CheckFile();
private readonly string _folderPath;
private readonly string _fileName;

public Serializer(string fileName)
        {
            _fileName = fileName;
            _folderPath = CreateFolderPath("Serializations");
        }   
файл та шлях до нього  задаеться в конструкторі і записує в відповідні властивості.
При потребі змінити шлях до файла можна реалізувати ще один конструктор але так як це непередбачається не завданням ні логікою я його нестворював.

public bool CheckFile()
        {           
            return File.Exists(Path.Combine(_folderPath, _fileName));
        }    
відповідно нема необхідності передавати шлях до файлу.

2021-05-29 07:00 UTC, wi9916 commented on Interfaces/ISerializable.cs
> +        bool CheckFile();
чи можливо прибрати bool CheckFile(); з інтерфейсу?

2021-05-29 22:07 UTC, serhii-shkodenko commented on Interfaces/ISerializable.cs
> +        T Desialization<T>(T obj);
Саме так, `Desialize`. Поправ, будь ласка.

2021-05-29 22:11 UTC, serhii-shkodenko commented on Interfaces/ISerializable.cs
> +        bool CheckFile();
Да, якщо ти вибрав варіант, коли шлях задається у конструкторі, я не бачу великого змісту у цьому методі без параметра. Тоді краще зробити його деталлю реалізації, тобто приватним і використовувати у публічних методах классу. Тоді з інтерфейсу можна будет прибрати.

2021-05-29 23:32 UTC, wi9916 commented on Interfaces/ISerializable.cs
> +        bool CheckFile();
var ser = new Serializer("customers");
            Customers = new List<Customer>();

            if (ser.CheckFile())
            {
                Customers = ser.Desialize(Customers);
            }
            else
            {
                CreateNewResidents();
                ser.Serialize(Customers);
            }

2021-05-29 23:34 UTC, wi9916 commented on Interfaces/ISerializable.cs
> +        bool CheckFile();
в мене ser.CheckFile() перевыряэ чи э файл для сереалызації. Приватним я його незроблю.

2021-05-29 23:46 UTC, wi9916 commented on Interfaces/ISerializable.cs
> +        bool CheckFile();
Хоча а якщо такий варіант?

2021-05-29 23:49 UTC, wi9916 commented on Interfaces/ISerializable.cs
> +        bool CheckFile();
if (!ser.Serialize(Foods))
                Foods = ser.Desialize(Foods);

2021-06-02 18:16 UTC, wi9916 commented
переробив

2021-06-02 20:56 UTC, serhii-shkodenko requested changes

2021-06-02 20:56 UTC, serhii-shkodenko commented on Interfaces/IResidentOperationable.cs
> +        bool CreateNewCustomer(Customer person);
Достатньо буде назвати `CreateCustomer()`.

2021-06-02 20:56 UTC, serhii-shkodenko commented on Interfaces/IResidentOperationable.cs
>          bool OutputInfoAboutCustomer();
Можна назвати лаконічніше: `GetCustomerInfo()`.

2021-06-02 20:56 UTC, serhii-shkodenko commented on Interfaces/IResidentOperationable.cs
>          bool OutputInfoAboutCustomer(int customerId);
Можна назвати більш змістовніше: `GetCustomerInfoById()`.

2021-06-02 20:56 UTC, serhii-shkodenko commented on Interfaces/IStoredOperationable.cs
> +        bool PutNewFood(Food food);
Буде достатньо назвати метод `AddFood()`.

2021-06-02 21:12 UTC, serhii-shkodenko requested changes

2021-06-02 21:12 UTC, serhii-shkodenko commented on Interfaces/ISerializable.cs
> +    public interface ISerializable
Завдання було створити механізм зберігання інформаціії на диску у серіалізований формі. Для серіалізації / десеріалізації даних вже є відповідні бібліотеки. Назва інтерфейсу і відповідного класу наштовхує на те, що вони реалізовують саме серіалізацію / десеріалізацію, а не зберігання. Це треба виправити.

2021-06-02 21:12 UTC, serhii-shkodenko commented on Services/Residents.cs
> +            var ser = new Serializer("customers");
Зчитування і наповнення сховища даними має здійснювати окремий клас. Його можна прокинути у якості залежності, зберегти у приватне поле і потім використоувати у методах твого сховищ: `SaveData()`, `LoadData()`, наприклад.

2021-06-03 09:47 UTC, wi9916 commented
Переробыв

2021-06-03 20:45 UTC, serhii-shkodenko requested changes
У коді я не бачу, як ти зберігаєш нові дані, або їх зміни. В задванні сказано, щоб це зберігалось.

2021-06-03 20:45 UTC, serhii-shkodenko commented on Services/Storage.cs
> +        public Storage(SerializeStorage serializeStorage)
Про Dependency inversion principle забув. Використовуй тут `ISerializeStoragable`.

2021-06-03 20:45 UTC, serhii-shkodenko commented on Services/Storage.cs
>              CreateNewBaseStorage();
Визову цього метода тут не має бути. Бо у разі розгортання твого додатку сховище буде забруднене цими дефолтними даними. Так не повинно бути. Зроби цей метод публічним і визивай у методі `Main`.

2021-06-03 20:45 UTC, serhii-shkodenko commented on Services/SerializeStorage.cs
> +        public bool Serialize<T>(T obj, bool rewriteFile = false)
Назва цього методу вкупі із параметрами звучить трохи дивно. Метод відсилає до серіалізації, а параметр вказує на якусь роботу із файлами. 

Ще раз наголошу, що формат зберігання у вигляді JSON - це деталь реалізації, про яку користувачі твого коду не повинні знати. Тому просто поприбирай згади про серілазацію / деверілазицію з методів та класів.

2021-06-03 20:45 UTC, serhii-shkodenko commented on Services/SerializeStorage.cs
> +        private string CreateFolderPath(string folderName)
Цей метод не створює папку, а лише генерує ім'я, треба прибрати слово `Create` і замінити його чимось іншим.

2021-06-04 12:00 UTC, wi9916 commented
переробив

2021-06-04 12:01 UTC, wi9916 commented on Services/Storage.cs
>              CreateNewBaseStorage();
переробив він викликається лище якщо нема сереалізованого файлу

2021-06-04 12:01 UTC, wi9916 commented on Services/Storage.cs
>              CreateNewBaseStorage();
відповідно створив метод перевірки наявності цього файлу

2021-06-06 10:12 UTC, serhii-shkodenko requested changes

2021-06-06 10:12 UTC, serhii-shkodenko commented on Interfaces/ISerializeStoragable.cs
> +    public interface ISerializeStoragable
Те, що під капотом відбувається серіалізація даних в Json це є в принципі деталлю реалізації, тому краще уникнути прямих посилань на це у назвах. Тому відповідно перейменуй, будь ласка, інтерфейс, класс, методи. Їх назви мають говорити про те, що вони роблять, а не як вони це роблять. У даному випадку просто зберігають якійсь дані.

2021-06-06 10:12 UTC, serhii-shkodenko commented on Services/SerializeStorage.cs
> +        private string CreateFolderPath(string folderName)
Не поправлено.

2021-06-06 10:12 UTC, serhii-shkodenko commented on Services/SerializeStorage.cs
> +        public bool Serialize<T>(T obj, bool rewriteFile = false)
Не поправлено.

2021-06-06 10:12 UTC, serhii-shkodenko commented
> переробив

Може ти переробив, і не запушив?

2021-06-06 10:15 UTC, wi9916 commented
дійсно((

2021-06-06 11:22 UTC, serhii-shkodenko requested changes

2021-06-06 11:22 UTC, serhii-shkodenko commented on Services/DataStorage.cs
> +            Speaker.Output("Serialization " +  obj.GetType(), "Serializer");
Прибери, будь ласка, залежність від UI шару. Він не має знати, що щось кудись записалоь чи ні. Його завдання - отримати дані від користувача і передати до бізнес шару.

2021-06-06 11:22 UTC, serhii-shkodenko commented on Services/DataStorage.cs
> +            Speaker.Output("Desialization " + obj.GetType(), "Serializer");
Прибери, будь ласка, залежність від UI шару. Він не має знати, що щось кудись записалоь чи ні. Його завдання - отримати дані від користувача і передати до бізнес шару.

2021-06-06 11:22 UTC, serhii-shkodenko commented on Services/Residents.cs
> +        public List<Customer> Customers { get; }
Цей клас в тебе містить бізнес логіку і немає зберігати даних. Ти маєш через методи цього класу звертатить до сховища і просити його надати дані/зберегти/змінити і таке інше. Саме в такому сховищі має зберігатися цей список.

2021-06-06 11:27 UTC, wi9916 commented on Services/Residents.cs
> +        public List<Customer> Customers { get; }
так це ы э клас для зберыгання данних

2021-06-06 11:27 UTC, wi9916 commented on Services/Residents.cs
> +        public List<Customer> Customers { get; }
ResidentsOperation вищій рівень

2021-06-06 11:34 UTC, wi9916 commented on Services/Residents.cs
> +        public List<Customer> Customers { get; }
а зверху ще є DialogInShop який імітує магазин

2021-06-06 11:35 UTC, wi9916 commented
виправив недоречне повідомлення про сиреалізацію і незовсім зрозумів про кастомер

2021-06-07 20:34 UTC, serhii-shkodenko commented on Services/Residents.cs
> +        public List<Customer> Customers { get; }
Це сервіс, він не має зберігати даних. Це поле треба прибрати.

2021-06-11 20:21 UTC, serhii-shkodenko approved these changes
Виглядає добре. Можна мержити.

2021-06-12 12:37 UTC, merged