Lecture10 cash
wi9916/RockFood pull request #7
Opened 2021-05-31 15:32 UTC by wi9916

2021-05-31 18:43 UTC, wi9916 commented
Delegate нефункционально а тільки для прикладу. Нічого не приходить в голову де іх можна використати з користю(((

2021-06-01 12:09 UTC, serhii-shkodenko requested changes

2021-06-01 12:09 UTC, serhii-shkodenko commented on Services/MemoryCache.cs
> +            if (!_cache.TryGetValue(key, out cacheEntry))
Тут можливий Race Condition, тому тут треба застосувати якийсь механізм блокування.

2021-06-01 12:09 UTC, serhii-shkodenko commented on Services/MemoryCache.cs
> +                cacheEntry = createItem();
Тут можливий Race Condition, тому тут треба застосувати якийсь механізм блокування. Між створенням елементу і його записом у кеш може пройти багато часу і конкуруючі потоки не будуть чекати завершення створення елементу і будуть намагатися його створити кожет.

2021-06-01 12:09 UTC, serhii-shkodenko commented on Services/ResidentsOperation.cs
> +        private readonly object _locker = new object();
Тут цей лок не потрібний.

2021-06-01 12:09 UTC, serhii-shkodenko commented on Services/ResidentsOperation.cs
> +                Task.Run( ()=>OutputInfoAboutCustomer(customer.Id) );
Тут цей fire and forget не потрібний.

2021-06-01 12:09 UTC, serhii-shkodenko commented on Services/ResidentsOperation.cs
> +            lock (_locker)
Тут цей лок непотрібний.

2021-06-01 12:09 UTC, serhii-shkodenko commented on Services/ResidentsOperation.cs
> +        public delegate void Del(IPersonable customer, string message);
Використання цього делегата новить сумнівний характер. Видали його, будь ласка.

2021-06-01 12:09 UTC, serhii-shkodenko commented on Services/StorageOperation.cs
> +        private readonly object _locker = new object();
Цей лок непотрібний.

2021-06-01 12:09 UTC, serhii-shkodenko commented on Services/StorageOperation.cs
> +            _memoryCach = new MemoryCache<IFoodable>();
Порушення dependency inversion principle.

2021-06-01 12:09 UTC, serhii-shkodenko commented on Services/ResidentsOperation.cs
> +            _memoryCach = new MemoryCache<IPersonable>();
Порушення dependency inversion principle.

2021-06-01 20:04 UTC, wi9916 commented on Services/ResidentsOperation.cs
> +                Task.Run( ()=>OutputInfoAboutCustomer(customer.Id) );
а тут нерозумію що нетак((( Можете пояснити?

2021-06-01 20:05 UTC, wi9916 commented on Services/ResidentsOperation.cs
> +                Task.Run( ()=>OutputInfoAboutCustomer(customer.Id) );
Task.Run( OutputInfoAboutCustomer(customer.Id) );

2021-06-01 20:05 UTC, serhii-shkodenko commented on Services/ResidentsOperation.cs
> +                Task.Run( ()=>OutputInfoAboutCustomer(customer.Id) );
Можливо, я неправльно зрозумів, твій намір у коді. Що ти тут робиш і навіщо?

2021-06-01 20:06 UTC, wi9916 commented on Services/ResidentsOperation.cs
> +                Task.Run( ()=>OutputInfoAboutCustomer(customer.Id) );
так працювати небуде((

2021-06-01 20:07 UTC, serhii-shkodenko commented on Services/ResidentsOperation.cs
> +                Task.Run( ()=>OutputInfoAboutCustomer(customer.Id) );
Яка мета цього рядка?
` Task.Run( ()=>OutputInfoAboutCustomer(customer.Id) );                       `

2021-06-01 20:10 UTC, wi9916 commented on Services/ResidentsOperation.cs
> +                Task.Run( ()=>OutputInfoAboutCustomer(customer.Id) );
створити потік для запиту

2021-06-01 20:12 UTC, wi9916 commented on Services/ResidentsOperation.cs
> +                Task.Run( ()=>OutputInfoAboutCustomer(customer.Id) );
там взагалі доречно використовувати потоки? чи краще однопоточно?

2021-06-01 20:50 UTC, serhii-shkodenko commented on Services/ResidentsOperation.cs
> +                Task.Run( ()=>OutputInfoAboutCustomer(customer.Id) );
Ні, не доречно. Саме тому зауважив.

2021-06-01 20:52 UTC, wi9916 commented on Services/ResidentsOperation.cs
> +                Task.Run( ()=>OutputInfoAboutCustomer(customer.Id) );
Добре перероблю в однопоточне

2021-06-02 18:12 UTC, wi9916 commented
переробив

2021-06-14 17:31 UTC, wi9916 commented
Переробыв

2021-07-11 15:12 UTC, serhii-shkodenko requested changes

2021-07-11 15:12 UTC, serhii-shkodenko commented on Services/MemoryCache.cs
> +    public class MemoryCache<TItem>
Додай будь ласка інтерфейс, щоб відповідати Dependency inversion principle. Використай цей інтерфейс у відповідних конструкторах.

2021-07-11 15:12 UTC, serhii-shkodenko commented on Services/MemoryCache.cs
> +                message = "Read from cache ";
Ти це тестував, в тебе вийшло отримати два повідомлення з метода?

2021-07-11 15:55 UTC, wi9916 commented on Services/MemoryCache.cs
> +                message = "Read from cache ";
да

2021-07-11 15:56 UTC, wi9916 commented on Services/MemoryCache.cs
> +                message = "Read from cache ";
![imgJPG](https://user-images.githubusercontent.com/45822095/125201889-be815800-e279-11eb-9c0a-9dd8dc57a9ed.jpg)

2021-07-11 15:57 UTC, wi9916 commented
обновив

2021-08-07 18:13 UTC, serhii-shkodenko requested changes
Поправ, будь ласка, ці зауваження і буде апрув.

2021-08-07 18:13 UTC, serhii-shkodenko commented on Services/ResidentsOperation.cs
> +            var customer = _memoryCach.GetOrCreate(customerId, () => GetObjectById(customerId), out message);
Одрук. Треба _memoryCach**e**

2021-08-07 18:13 UTC, serhii-shkodenko commented on Services/StorageOperation.cs
> +        private readonly MemoryCachable<IFoodable> _memoryCach;
Одрук. Треба _memoryCach**e**

2021-08-07 18:13 UTC, serhii-shkodenko commented on Services/StorageOperation.cs
> +            _storage.Foods = _dateStorage.LoadData(_storage.Foods);
Це погана ідея ініціалізувати дані прямо в конструкторі. Тобі ці дані потрібні у двох методах і до того моменту, поки ти вирішиш викликати методи, ці дані вже можуть застаріти. Виходить, що окрім кешу, в тебе є ще щось типу кешу, але він ніяк не інвалідується. Тому просто прибери цю ініціалазацію і викликай `LoadData`, наприклад, після створення об'єкта `DataStorage` у методі Main.

2021-08-07 18:13 UTC, serhii-shkodenko commented on Services/StorageOperation.cs
> +            _storage.Foods = _dateStorage.LoadData(_storage.Foods);
Одрук, треба _dat**a**Storage.

2021-08-07 18:13 UTC, serhii-shkodenko commented on Services/ResidentsOperation.cs
>              _storage.Customers = _dateStorage.LoadData(_storage.Customers);
Це погана ідея ініціалізувати дані прямо в конструкторі. Тобі ці дані потрібні у двох методах і до того моменту, поки ти вирішиш викликати методи, ці дані вже можуть застаріти. Виходить, що окрім кешу, в тебе є ще щось типу кешу, але він ніяк не інвалідується. Тому просто прибери цю ініціалазацію і викликай `LoadData`, наприклад, після створення об'єкта `DataStorage` у методі Main.

2021-08-07 18:13 UTC, serhii-shkodenko commented on Services/ResidentsOperation.cs
> +        public void GetCustomerInfo()
Краще переназвати, використавши Output, як ти це зробив в іншому класі.

2021-08-07 18:13 UTC, serhii-shkodenko commented on Services/ResidentsOperation.cs
>              _storage.Customers = _dateStorage.LoadData(_storage.Customers);
Одрук, треба _dat**a**Storage.

2021-08-08 19:04 UTC, wi9916 commented
Выправив

2021-08-09 06:14 UTC, serhii-shkodenko approved these changes
Виглядає добре, можна мержити.

2021-08-11 13:56 UTC, merged